import { PrismaClient } from "@prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import path from "path";

const dbPath = path.resolve(process.cwd(), "prisma", "dev.db");
const adapter = new PrismaLibSql({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

async function main() {
  // Create categories
  const categories = await Promise.all([
    prisma.plantCategory.upsert({
      where: { name: "Plantes tropicales" },
      update: {},
      create: { name: "Plantes tropicales", icon: "🌴" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Succulentes & Cactus" },
      update: {},
      create: { name: "Succulentes & Cactus", icon: "🌵" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Plantes grimpantes" },
      update: {},
      create: { name: "Plantes grimpantes", icon: "🌿" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Fougères" },
      update: {},
      create: { name: "Fougères", icon: "🌾" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Plantes fleuries" },
      update: {},
      create: { name: "Plantes fleuries", icon: "🌸" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Arbres d'intérieur" },
      update: {},
      create: { name: "Arbres d'intérieur", icon: "🌳" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Plantes aromatiques" },
      update: {},
      create: { name: "Plantes aromatiques", icon: "🌱" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Palmiers" },
      update: {},
      create: { name: "Palmiers", icon: "🌴" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Plantes carnivores" },
      update: {},
      create: { name: "Plantes carnivores", icon: "🪴" },
    }),
    prisma.plantCategory.upsert({
      where: { name: "Orchidées" },
      update: {},
      create: { name: "Orchidées", icon: "🌺" },
    }),
  ]);

  const [tropical, succulents, climbing, ferns, flowering, trees, aromatic, palms, carnivorous, orchids] = categories;

  // Comprehensive plant library
  const plants = [
    // Tropical plants
    {
      commonName: "Monstera deliciosa",
      scientificName: "Monstera deliciosa",
      family: "Araceae",
      description: "Plante tropicale iconique avec de grandes feuilles perforées. Croissance vigoureuse et facile d'entretien.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "fast",
      maxHeight: "3m en intérieur",
      origin: "Amérique centrale",
      lightMin: 2, lightMax: 4,
      lightDescription: "Lumière indirecte vive. Tolère l'ombre légère.",
      wateringFrequency: "Arroser quand le substrat est sec sur 2-3cm",
      wateringFreqDays: 7,
      humidityMin: 50, humidityMax: 80,
      tempMin: 15, tempMax: 30, tempIdealMin: 20, tempIdealMax: 25,
      fertilizerType: "Engrais équilibré liquide",
      fertilizerFreqDays: 14,
      fertilizerNPK: "20-20-20",
      fertilizerNotes: "Réduire en hiver. Ne pas fertiliser les 6 premières semaines après rempotage.",
      fertilizerDoseMLPerLiter: 1.0,
      preferredSubstrate: "Mélange drainant: terreau, perlite, écorces",
      soilPH: "5.5-7.0",
      drainageNeeds: "high",
      categoryId: tropical.id,
    },
    {
      commonName: "Philodendron scandens",
      scientificName: "Philodendron hederaceum",
      family: "Araceae",
      description: "Plante grimpante ou retombante aux feuilles en forme de cœur. Très résistante et adaptable.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "fast",
      maxHeight: "4m (retombant)",
      origin: "Amérique du Sud",
      lightMin: 2, lightMax: 4,
      lightDescription: "Lumière indirecte moyenne à vive. Survit en faible lumière.",
      wateringFrequency: "Arroser quand le substrat est sec sur 2cm",
      wateringFreqDays: 5,
      humidityMin: 40, humidityMax: 70,
      tempMin: 15, tempMax: 30, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais liquide pour plantes vertes",
      fertilizerFreqDays: 14,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Diluer à moitié en hiver",
      fertilizerDoseMLPerLiter: 0.8,
      preferredSubstrate: "Terreau léger avec perlite",
      soilPH: "5.0-6.0",
      drainageNeeds: "medium",
      categoryId: tropical.id,
    },
    {
      commonName: "Alocasia Polly",
      scientificName: "Alocasia amazonica",
      family: "Araceae",
      description: "Plante tropicale aux feuilles sombres en forme de flèche avec des nervures argentées spectaculaires.",
      difficulty: "hard",
      toxicity: "moderate",
      growthRate: "medium",
      maxHeight: "60cm",
      origin: "Asie du Sud-Est",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière indirecte vive. Pas de soleil direct.",
      wateringFrequency: "Maintenir le substrat légèrement humide sans détremper",
      wateringFreqDays: 4,
      humidityMin: 60, humidityMax: 90,
      tempMin: 18, tempMax: 30, tempIdealMin: 20, tempIdealMax: 27,
      fertilizerType: "Engrais liquide riche en azote",
      fertilizerFreqDays: 14,
      fertilizerNPK: "20-10-10",
      fertilizerNotes: "Fertiliser uniquement en période de croissance (mars-octobre)",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Mélange aéré: perlite, écorce, sphaigne",
      soilPH: "5.5-6.5",
      drainageNeeds: "high",
      categoryId: tropical.id,
    },
    {
      commonName: "Calathea orbifolia",
      scientificName: "Goeppertia orbifolia",
      family: "Marantaceae",
      description: "Superbes feuilles rondes striées d'argent. Plante exigeante qui récompense les soins attentifs.",
      difficulty: "hard",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "1m",
      origin: "Brésil",
      lightMin: 2, lightMax: 3,
      lightDescription: "Lumière indirecte moyenne. Pas de soleil direct.",
      wateringFrequency: "Maintenir humide. Utiliser de l'eau filtrée ou de pluie.",
      wateringFreqDays: 3,
      humidityMin: 60, humidityMax: 90,
      tempMin: 16, tempMax: 27, tempIdealMin: 18, tempIdealMax: 24,
      fertilizerType: "Engrais dilué pour plantes vertes",
      fertilizerFreqDays: 30,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Très sensible aux sels. Fertiliser faiblement et rarement.",
      fertilizerDoseMLPerLiter: 0.3,
      preferredSubstrate: "Terreau tourbe, perlite, coco",
      soilPH: "6.0-7.0",
      drainageNeeds: "medium",
      categoryId: tropical.id,
    },
    {
      commonName: "Strelitzia nicolai",
      scientificName: "Strelitzia nicolai",
      family: "Strelitziaceae",
      description: "Oiseau du paradis géant. Grandes feuilles en éventail créant une ambiance tropicale.",
      difficulty: "medium",
      toxicity: "mild",
      growthRate: "fast",
      maxHeight: "3m en intérieur",
      origin: "Afrique du Sud",
      lightMin: 4, lightMax: 5,
      lightDescription: "Plein soleil ou lumière très vive. Accepte quelques heures de soleil direct.",
      wateringFrequency: "Arroser abondamment puis laisser sécher",
      wateringFreqDays: 7,
      humidityMin: 40, humidityMax: 70,
      tempMin: 10, tempMax: 35, tempIdealMin: 18, tempIdealMax: 28,
      fertilizerType: "Engrais riche pour plantes vertes",
      fertilizerFreqDays: 14,
      fertilizerNPK: "15-10-15",
      fertilizerNotes: "Gros appétit en période de croissance",
      fertilizerDoseMLPerLiter: 1.5,
      preferredSubstrate: "Terreau riche avec drainage",
      soilPH: "5.5-7.5",
      drainageNeeds: "high",
      categoryId: tropical.id,
    },
    {
      commonName: "Anthurium clarinervium",
      scientificName: "Anthurium clarinervium",
      family: "Araceae",
      description: "Feuilles veloutées en forme de cœur avec nervures blanches contrastantes. Pièce de collection.",
      difficulty: "medium",
      toxicity: "mild",
      growthRate: "slow",
      maxHeight: "60cm",
      origin: "Mexique",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière indirecte vive",
      wateringFrequency: "Laisser sécher légèrement entre les arrosages",
      wateringFreqDays: 5,
      humidityMin: 60, humidityMax: 85,
      tempMin: 16, tempMax: 28, tempIdealMin: 20, tempIdealMax: 25,
      fertilizerType: "Engrais orchidées dilué",
      fertilizerFreqDays: 21,
      fertilizerNPK: "20-20-20",
      fertilizerNotes: "Dose très réduite. Sensible à la sur-fertilisation.",
      fertilizerDoseMLPerLiter: 0.3,
      preferredSubstrate: "Mélange très aéré: écorce, sphaigne, perlite, charbon",
      soilPH: "5.5-6.5",
      drainageNeeds: "high",
      categoryId: tropical.id,
    },
    // Succulents & Cactus
    {
      commonName: "Echeveria elegans",
      scientificName: "Echeveria elegans",
      family: "Crassulaceae",
      description: "Rosette compacte de feuilles charnues bleu-gris. Très décorative et facile.",
      difficulty: "easy",
      toxicity: "none",
      growthRate: "slow",
      maxHeight: "15cm",
      origin: "Mexique",
      lightMin: 4, lightMax: 5,
      lightDescription: "Plein soleil nécessaire. Minimum 6h de lumière directe.",
      wateringFrequency: "Laisser sécher complètement entre les arrosages",
      wateringFreqDays: 14,
      humidityMin: 20, humidityMax: 50,
      tempMin: 5, tempMax: 35, tempIdealMin: 18, tempIdealMax: 28,
      fertilizerType: "Engrais cactus/succulentes",
      fertilizerFreqDays: 30,
      fertilizerNPK: "5-10-10",
      fertilizerNotes: "Uniquement au printemps et en été. Dose très réduite.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Substrat minéral: pomice, gravier, sable grossier",
      soilPH: "6.0-7.0",
      drainageNeeds: "high",
      categoryId: succulents.id,
    },
    {
      commonName: "Aloe vera",
      scientificName: "Aloe barbadensis miller",
      family: "Asphodelaceae",
      description: "Succulente médicinale aux feuilles épaisses remplies de gel. Très résistante à la sécheresse.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "medium",
      maxHeight: "60cm",
      origin: "Péninsule arabique",
      lightMin: 4, lightMax: 5,
      lightDescription: "Lumière vive à soleil direct. Éviter le soleil brûlant en été.",
      wateringFrequency: "Arroser profondément puis laisser sécher complètement",
      wateringFreqDays: 14,
      humidityMin: 20, humidityMax: 50,
      tempMin: 8, tempMax: 35, tempIdealMin: 18, tempIdealMax: 28,
      fertilizerType: "Engrais succulentes dilué",
      fertilizerFreqDays: 30,
      fertilizerNPK: "10-40-10",
      fertilizerNotes: "Fertiliser peu. Une fois par mois au printemps/été seulement.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Terreau cactus avec perlite ou sable grossier",
      soilPH: "7.0-8.5",
      drainageNeeds: "high",
      categoryId: succulents.id,
    },
    {
      commonName: "Cactus San Pedro",
      scientificName: "Echinopsis pachanoi",
      family: "Cactaceae",
      description: "Grand cactus colonnaire à croissance rapide. Impressionnant et très facile d'entretien.",
      difficulty: "easy",
      toxicity: "moderate",
      growthRate: "fast",
      maxHeight: "3m en pot",
      origin: "Andes (Pérou, Équateur)",
      lightMin: 4, lightMax: 5,
      lightDescription: "Plein soleil. Nécessite un maximum de lumière.",
      wateringFrequency: "Arroser généreusement en été, très peu en hiver",
      wateringFreqDays: 10,
      humidityMin: 20, humidityMax: 40,
      tempMin: 5, tempMax: 40, tempIdealMin: 18, tempIdealMax: 30,
      fertilizerType: "Engrais cactus riche en potassium",
      fertilizerFreqDays: 14,
      fertilizerNPK: "5-5-15",
      fertilizerNotes: "Fertiliser régulièrement en été pour une croissance optimale",
      fertilizerDoseMLPerLiter: 1.0,
      preferredSubstrate: "Substrat très minéral: 70% pomice/perlite, 30% terreau",
      soilPH: "6.0-7.5",
      drainageNeeds: "high",
      categoryId: succulents.id,
    },
    {
      commonName: "Haworthia fasciata",
      scientificName: "Haworthiopsis fasciata",
      family: "Asphodelaceae",
      description: "Petite succulente avec des bandes blanches horizontales. Parfaite pour les rebords de fenêtre.",
      difficulty: "easy",
      toxicity: "none",
      growthRate: "slow",
      maxHeight: "15cm",
      origin: "Afrique du Sud",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière vive indirecte. Tolère un peu de soleil direct le matin.",
      wateringFrequency: "Laisser sécher entre les arrosages",
      wateringFreqDays: 10,
      humidityMin: 30, humidityMax: 50,
      tempMin: 8, tempMax: 30, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais succulentes très dilué",
      fertilizerFreqDays: 30,
      fertilizerNPK: "5-10-10",
      fertilizerNotes: "Fertiliser très peu. Printemps uniquement.",
      fertilizerDoseMLPerLiter: 0.3,
      preferredSubstrate: "Substrat minéral très drainant",
      soilPH: "6.5-7.5",
      drainageNeeds: "high",
      categoryId: succulents.id,
    },
    // Climbing plants
    {
      commonName: "Pothos doré",
      scientificName: "Epipremnum aureum",
      family: "Araceae",
      description: "Plante grimpante ou retombante extrêmement résistante. Idéale pour les débutants.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "fast",
      maxHeight: "10m (grimpant)",
      origin: "Polynésie française",
      lightMin: 1, lightMax: 4,
      lightDescription: "Très adaptable. De la faible lumière à la lumière vive indirecte.",
      wateringFrequency: "Laisser sécher sur 2-3cm entre les arrosages",
      wateringFreqDays: 7,
      humidityMin: 30, humidityMax: 70,
      tempMin: 12, tempMax: 30, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais liquide équilibré",
      fertilizerFreqDays: 14,
      fertilizerNPK: "20-20-20",
      fertilizerNotes: "Fertiliser au printemps/été. Arrêter en hiver.",
      fertilizerDoseMLPerLiter: 1.0,
      preferredSubstrate: "Terreau universel avec perlite",
      soilPH: "6.0-6.5",
      drainageNeeds: "medium",
      categoryId: climbing.id,
    },
    {
      commonName: "Hoya carnosa",
      scientificName: "Hoya carnosa",
      family: "Apocynaceae",
      description: "Plante grimpante à fleurs cireuses étoilées parfumées. Feuillage succulent.",
      difficulty: "medium",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "3m",
      origin: "Asie de l'Est",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière indirecte vive. Un peu de soleil matinal favorise la floraison.",
      wateringFrequency: "Laisser sécher entre les arrosages. Réduire beaucoup en hiver.",
      wateringFreqDays: 10,
      humidityMin: 40, humidityMax: 70,
      tempMin: 10, tempMax: 30, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais riche en potassium pour floraison",
      fertilizerFreqDays: 21,
      fertilizerNPK: "10-10-20",
      fertilizerNotes: "Fertiliser en période de croissance. Favorise la floraison.",
      fertilizerDoseMLPerLiter: 0.8,
      preferredSubstrate: "Substrat bien drainant: écorce, perlite, terreau",
      soilPH: "6.0-7.0",
      drainageNeeds: "high",
      categoryId: climbing.id,
    },
    {
      commonName: "Monstera adansonii",
      scientificName: "Monstera adansonii",
      family: "Araceae",
      description: "Monstera grimpante aux feuilles perforées élégantes. Croissance rapide sur tuteur.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "fast",
      maxHeight: "5m (grimpant)",
      origin: "Amérique du Sud",
      lightMin: 2, lightMax: 4,
      lightDescription: "Lumière indirecte vive. Éviter le soleil direct.",
      wateringFrequency: "Arroser quand le substrat est sec en surface",
      wateringFreqDays: 5,
      humidityMin: 50, humidityMax: 80,
      tempMin: 15, tempMax: 30, tempIdealMin: 20, tempIdealMax: 27,
      fertilizerType: "Engrais liquide plantes vertes",
      fertilizerFreqDays: 14,
      fertilizerNPK: "20-20-20",
      fertilizerNotes: "Fertiliser régulièrement en saison de croissance",
      fertilizerDoseMLPerLiter: 1.0,
      preferredSubstrate: "Mélange aéré avec écorce et perlite",
      soilPH: "5.5-7.0",
      drainageNeeds: "high",
      categoryId: climbing.id,
    },
    // Ferns
    {
      commonName: "Fougère de Boston",
      scientificName: "Nephrolepis exaltata",
      family: "Nephrolepidaceae",
      description: "Fougère retombante luxuriante. Excellente pour purifier l'air.",
      difficulty: "medium",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "1m",
      origin: "Régions tropicales",
      lightMin: 2, lightMax: 3,
      lightDescription: "Lumière indirecte. Pas de soleil direct.",
      wateringFrequency: "Maintenir le substrat toujours légèrement humide",
      wateringFreqDays: 3,
      humidityMin: 60, humidityMax: 90,
      tempMin: 12, tempMax: 25, tempIdealMin: 16, tempIdealMax: 22,
      fertilizerType: "Engrais dilué pour plantes vertes",
      fertilizerFreqDays: 30,
      fertilizerNPK: "20-10-20",
      fertilizerNotes: "Fertiliser faiblement. Sensible aux excès de sel.",
      fertilizerDoseMLPerLiter: 0.3,
      preferredSubstrate: "Terreau riche en matière organique, tourbe",
      soilPH: "5.0-5.5",
      drainageNeeds: "medium",
      categoryId: ferns.id,
    },
    {
      commonName: "Fougère nid d'oiseau",
      scientificName: "Asplenium nidus",
      family: "Aspleniaceae",
      description: "Fougère aux frondes entières ondulées formant un nid. Très décorative.",
      difficulty: "medium",
      toxicity: "none",
      growthRate: "slow",
      maxHeight: "1.2m",
      origin: "Asie tropicale",
      lightMin: 2, lightMax: 3,
      lightDescription: "Lumière indirecte moyenne. Ombre partielle.",
      wateringFrequency: "Maintenir humide. Ne jamais verser d'eau au centre de la rosette.",
      wateringFreqDays: 4,
      humidityMin: 50, humidityMax: 80,
      tempMin: 15, tempMax: 28, tempIdealMin: 18, tempIdealMax: 24,
      fertilizerType: "Engrais liquide très dilué",
      fertilizerFreqDays: 30,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Fertiliser très peu. Appliquer sur le substrat, jamais sur les feuilles.",
      fertilizerDoseMLPerLiter: 0.3,
      preferredSubstrate: "Terreau fibreux riche en humus",
      soilPH: "5.0-5.5",
      drainageNeeds: "medium",
      categoryId: ferns.id,
    },
    {
      commonName: "Fougère de Maidenhair",
      scientificName: "Adiantum raddianum",
      family: "Pteridaceae",
      description: "Fougère délicate aux frondes fines et aériennes. Exigeante mais magnifique.",
      difficulty: "hard",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "50cm",
      origin: "Amérique tropicale",
      lightMin: 2, lightMax: 3,
      lightDescription: "Lumière indirecte douce. Éviter absolument le soleil direct.",
      wateringFrequency: "Ne jamais laisser sécher. Humidité constante.",
      wateringFreqDays: 2,
      humidityMin: 70, humidityMax: 95,
      tempMin: 15, tempMax: 25, tempIdealMin: 18, tempIdealMax: 22,
      fertilizerType: "Engrais très dilué",
      fertilizerFreqDays: 30,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "À peine fertiliser. Très sensible aux sels minéraux.",
      fertilizerDoseMLPerLiter: 0.2,
      preferredSubstrate: "Terreau riche, tourbe, maintenu humide",
      soilPH: "5.5-6.0",
      drainageNeeds: "low",
      categoryId: ferns.id,
    },
    // Flowering plants
    {
      commonName: "Spathiphyllum",
      scientificName: "Spathiphyllum wallisii",
      family: "Araceae",
      description: "Fleur de lune élégante aux spathes blanches. Excellente purificatrice d'air.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "medium",
      maxHeight: "80cm",
      origin: "Amérique tropicale",
      lightMin: 1, lightMax: 3,
      lightDescription: "Faible à moyenne lumière indirecte. Tolère l'ombre.",
      wateringFrequency: "Arroser quand les feuilles commencent à s'affaisser légèrement",
      wateringFreqDays: 5,
      humidityMin: 40, humidityMax: 70,
      tempMin: 15, tempMax: 28, tempIdealMin: 18, tempIdealMax: 24,
      fertilizerType: "Engrais plantes fleuries",
      fertilizerFreqDays: 14,
      fertilizerNPK: "10-20-15",
      fertilizerNotes: "Fertiliser régulièrement pour favoriser la floraison",
      fertilizerDoseMLPerLiter: 0.8,
      preferredSubstrate: "Terreau riche bien drainant",
      soilPH: "5.0-6.5",
      drainageNeeds: "medium",
      categoryId: flowering.id,
    },
    {
      commonName: "Anthurium rouge",
      scientificName: "Anthurium andraeanum",
      family: "Araceae",
      description: "Spathes rouge vif cireuses très décoratives. Floraison presque continue.",
      difficulty: "medium",
      toxicity: "mild",
      growthRate: "medium",
      maxHeight: "60cm",
      origin: "Colombie, Équateur",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière indirecte vive pour une bonne floraison.",
      wateringFrequency: "Arroser quand le substrat est sec en surface",
      wateringFreqDays: 5,
      humidityMin: 60, humidityMax: 80,
      tempMin: 16, tempMax: 28, tempIdealMin: 20, tempIdealMax: 25,
      fertilizerType: "Engrais plantes fleuries riche en phosphore",
      fertilizerFreqDays: 14,
      fertilizerNPK: "10-30-20",
      fertilizerNotes: "Fertiliser régulièrement pour une floraison continue",
      fertilizerDoseMLPerLiter: 0.8,
      preferredSubstrate: "Mélange orchidée / perlite / terreau",
      soilPH: "5.5-6.5",
      drainageNeeds: "high",
      categoryId: flowering.id,
    },
    {
      commonName: "Cyclamen",
      scientificName: "Cyclamen persicum",
      family: "Primulaceae",
      description: "Plante à bulbe aux fleurs élégantes retournées. Floraison hivernale.",
      difficulty: "medium",
      toxicity: "moderate",
      growthRate: "medium",
      maxHeight: "30cm",
      origin: "Méditerranée orientale",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière vive indirecte. Fraîcheur nécessaire.",
      wateringFrequency: "Arroser par le bas. Ne pas mouiller le bulbe.",
      wateringFreqDays: 4,
      humidityMin: 40, humidityMax: 60,
      tempMin: 8, tempMax: 18, tempIdealMin: 10, tempIdealMax: 16,
      fertilizerType: "Engrais plantes fleuries",
      fertilizerFreqDays: 14,
      fertilizerNPK: "10-20-20",
      fertilizerNotes: "Fertiliser pendant la croissance et floraison. Arrêter en dormance.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Terreau léger et bien drainé",
      soilPH: "6.0-7.0",
      drainageNeeds: "high",
      categoryId: flowering.id,
    },
    // Indoor trees
    {
      commonName: "Ficus lyrata",
      scientificName: "Ficus lyrata",
      family: "Moraceae",
      description: "Arbre d'intérieur majestueux aux grandes feuilles en forme de lyre. Très tendance.",
      difficulty: "medium",
      toxicity: "mild",
      growthRate: "medium",
      maxHeight: "3m en intérieur",
      origin: "Afrique de l'Ouest",
      lightMin: 3, lightMax: 5,
      lightDescription: "Lumière vive. Quelques heures de soleil direct bénéfiques.",
      wateringFrequency: "Arroser quand le substrat est sec sur 3-5cm",
      wateringFreqDays: 7,
      humidityMin: 40, humidityMax: 65,
      tempMin: 15, tempMax: 30, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais plantes vertes liquide",
      fertilizerFreqDays: 14,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Fertiliser au printemps et en été. Arrêter en automne/hiver.",
      fertilizerDoseMLPerLiter: 1.0,
      preferredSubstrate: "Terreau drainant avec perlite",
      soilPH: "6.0-7.0",
      drainageNeeds: "high",
      categoryId: trees.id,
    },
    {
      commonName: "Ficus elastica",
      scientificName: "Ficus elastica",
      family: "Moraceae",
      description: "Caoutchouc d'intérieur aux feuilles épaisses et brillantes. Robuste et élégant.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "medium",
      maxHeight: "3m en intérieur",
      origin: "Asie du Sud-Est",
      lightMin: 3, lightMax: 5,
      lightDescription: "Lumière vive. Tolère un peu de soleil direct.",
      wateringFrequency: "Arroser quand le substrat est sec sur 3-4cm",
      wateringFreqDays: 7,
      humidityMin: 30, humidityMax: 60,
      tempMin: 12, tempMax: 30, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais plantes vertes",
      fertilizerFreqDays: 14,
      fertilizerNPK: "15-10-10",
      fertilizerNotes: "Fertiliser en période de croissance",
      fertilizerDoseMLPerLiter: 1.0,
      preferredSubstrate: "Terreau universel avec perlite",
      soilPH: "6.0-7.0",
      drainageNeeds: "medium",
      categoryId: trees.id,
    },
    {
      commonName: "Pachira aquatica",
      scientificName: "Pachira aquatica",
      family: "Malvaceae",
      description: "Arbre d'intérieur au tronc tressé caractéristique. Symbole de prospérité.",
      difficulty: "easy",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "2.5m en intérieur",
      origin: "Amérique centrale",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière indirecte vive. Éviter le soleil direct prolongé.",
      wateringFrequency: "Arroser quand le substrat est sec. Tolère la sécheresse.",
      wateringFreqDays: 10,
      humidityMin: 40, humidityMax: 70,
      tempMin: 12, tempMax: 28, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais équilibré liquide",
      fertilizerFreqDays: 21,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Fertiliser modérément au printemps/été",
      fertilizerDoseMLPerLiter: 0.8,
      preferredSubstrate: "Terreau drainant avec sable",
      soilPH: "6.0-7.5",
      drainageNeeds: "high",
      categoryId: trees.id,
    },
    // Aromatic
    {
      commonName: "Basilic",
      scientificName: "Ocimum basilicum",
      family: "Lamiaceae",
      description: "Herbe aromatique incontournable. Parfum intense, idéale en cuisine.",
      difficulty: "easy",
      toxicity: "none",
      growthRate: "fast",
      maxHeight: "60cm",
      origin: "Inde",
      lightMin: 4, lightMax: 5,
      lightDescription: "Plein soleil. Minimum 6-8h de lumière directe.",
      wateringFrequency: "Maintenir le substrat légèrement humide",
      wateringFreqDays: 2,
      humidityMin: 40, humidityMax: 60,
      tempMin: 15, tempMax: 35, tempIdealMin: 20, tempIdealMax: 28,
      fertilizerType: "Engrais organique liquide",
      fertilizerFreqDays: 14,
      fertilizerNPK: "5-5-5",
      fertilizerNotes: "Fertiliser légèrement. Trop d'azote réduit la saveur.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Terreau léger bien drainé",
      soilPH: "6.0-7.0",
      drainageNeeds: "medium",
      categoryId: aromatic.id,
    },
    {
      commonName: "Romarin",
      scientificName: "Salvia rosmarinus",
      family: "Lamiaceae",
      description: "Arbuste aromatique méditerranéen persistant. Résistant et très parfumé.",
      difficulty: "easy",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "1.5m",
      origin: "Méditerranée",
      lightMin: 5, lightMax: 5,
      lightDescription: "Plein soleil indispensable. Maximum de lumière.",
      wateringFrequency: "Laisser sécher entre les arrosages. Résiste à la sécheresse.",
      wateringFreqDays: 10,
      humidityMin: 20, humidityMax: 50,
      tempMin: -5, tempMax: 35, tempIdealMin: 15, tempIdealMax: 28,
      fertilizerType: "Engrais très léger",
      fertilizerFreqDays: 30,
      fertilizerNPK: "5-5-5",
      fertilizerNotes: "Peu exigeant. Fertiliser à peine au printemps.",
      fertilizerDoseMLPerLiter: 0.3,
      preferredSubstrate: "Substrat minéral pauvre: sable, gravier, terreau",
      soilPH: "6.0-8.0",
      drainageNeeds: "high",
      categoryId: aromatic.id,
    },
    // Palms
    {
      commonName: "Areca",
      scientificName: "Dypsis lutescens",
      family: "Arecaceae",
      description: "Palmier d'intérieur élégant aux frondes arquées. Excellent purificateur d'air.",
      difficulty: "medium",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "2.5m en intérieur",
      origin: "Madagascar",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière indirecte vive. Pas de soleil direct.",
      wateringFrequency: "Maintenir le substrat légèrement humide. Ne pas détremper.",
      wateringFreqDays: 5,
      humidityMin: 50, humidityMax: 70,
      tempMin: 15, tempMax: 30, tempIdealMin: 20, tempIdealMax: 25,
      fertilizerType: "Engrais palmier",
      fertilizerFreqDays: 14,
      fertilizerNPK: "12-4-12",
      fertilizerNotes: "Fertiliser régulièrement au printemps/été avec engrais spécial palmier",
      fertilizerDoseMLPerLiter: 1.0,
      preferredSubstrate: "Terreau drainant enrichi",
      soilPH: "6.0-7.0",
      drainageNeeds: "high",
      categoryId: palms.id,
    },
    {
      commonName: "Kentia",
      scientificName: "Howea forsteriana",
      family: "Arecaceae",
      description: "Palmier d'intérieur par excellence. Élégant, résistant, tolère l'ombre.",
      difficulty: "easy",
      toxicity: "none",
      growthRate: "slow",
      maxHeight: "3m en intérieur",
      origin: "Île Lord Howe (Australie)",
      lightMin: 2, lightMax: 4,
      lightDescription: "Lumière indirecte. Tolère l'ombre.",
      wateringFrequency: "Arroser quand le substrat est sec en surface",
      wateringFreqDays: 7,
      humidityMin: 40, humidityMax: 60,
      tempMin: 12, tempMax: 28, tempIdealMin: 18, tempIdealMax: 24,
      fertilizerType: "Engrais palmier équilibré",
      fertilizerFreqDays: 21,
      fertilizerNPK: "12-4-12",
      fertilizerNotes: "Fertiliser modérément au printemps/été",
      fertilizerDoseMLPerLiter: 0.8,
      preferredSubstrate: "Terreau riche bien drainé",
      soilPH: "6.0-6.5",
      drainageNeeds: "medium",
      categoryId: palms.id,
    },
    // Carnivorous
    {
      commonName: "Dionée attrape-mouches",
      scientificName: "Dionaea muscipula",
      family: "Droseraceae",
      description: "La plante carnivore la plus connue. Pièges à mâchoires fascinants.",
      difficulty: "hard",
      toxicity: "none",
      growthRate: "slow",
      maxHeight: "15cm",
      origin: "Caroline du Nord/Sud (USA)",
      lightMin: 5, lightMax: 5,
      lightDescription: "Plein soleil direct indispensable. Minimum 6h.",
      wateringFrequency: "Maintenir la soucoupe pleine d'eau de pluie ou déminéralisée",
      wateringFreqDays: 1,
      humidityMin: 50, humidityMax: 90,
      tempMin: 0, tempMax: 35, tempIdealMin: 20, tempIdealMax: 28,
      fertilizerType: "AUCUN",
      fertilizerFreqDays: 0,
      fertilizerNPK: "0-0-0",
      fertilizerNotes: "NE JAMAIS fertiliser. Les proies suffisent. L'engrais tue la plante.",
      fertilizerDoseMLPerLiter: 0,
      preferredSubstrate: "Tourbe blonde pure ou sphaigne vivante",
      soilPH: "3.5-5.0",
      drainageNeeds: "low",
      categoryId: carnivorous.id,
    },
    {
      commonName: "Nepenthes",
      scientificName: "Nepenthes ventricosa",
      family: "Nepenthaceae",
      description: "Plante à urnes tropicale. Pièges en forme de cruches spectaculaires.",
      difficulty: "medium",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "1m (retombant)",
      origin: "Philippines",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière vive indirecte. Éviter le soleil direct brûlant.",
      wateringFrequency: "Maintenir humide. Eau de pluie ou déminéralisée de préférence.",
      wateringFreqDays: 3,
      humidityMin: 60, humidityMax: 90,
      tempMin: 15, tempMax: 30, tempIdealMin: 20, tempIdealMax: 28,
      fertilizerType: "Très dilué optionnel",
      fertilizerFreqDays: 30,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Optionnel. Si utilisé, diluer 10x la dose normale. Appliquer dans les urnes.",
      fertilizerDoseMLPerLiter: 0.1,
      preferredSubstrate: "Sphaigne, perlite, écorce",
      soilPH: "4.5-5.5",
      drainageNeeds: "medium",
      categoryId: carnivorous.id,
    },
    // Orchids
    {
      commonName: "Phalaenopsis",
      scientificName: "Phalaenopsis spp.",
      family: "Orchidaceae",
      description: "Orchidée papillon. La plus populaire et la plus facile des orchidées.",
      difficulty: "easy",
      toxicity: "none",
      growthRate: "slow",
      maxHeight: "50cm",
      origin: "Asie du Sud-Est",
      lightMin: 2, lightMax: 3,
      lightDescription: "Lumière indirecte. Pas de soleil direct.",
      wateringFrequency: "Trempage 15min puis séchage complet. Racines argent = soif.",
      wateringFreqDays: 7,
      humidityMin: 50, humidityMax: 70,
      tempMin: 15, tempMax: 28, tempIdealMin: 20, tempIdealMax: 25,
      fertilizerType: "Engrais orchidées",
      fertilizerFreqDays: 14,
      fertilizerNPK: "20-20-20",
      fertilizerNotes: "Fertiliser à chaque arrosage sauf un (flush). Réduire en hiver.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Écorce de pin, sphaigne, charbon",
      soilPH: "5.5-6.5",
      drainageNeeds: "high",
      categoryId: orchids.id,
    },
    {
      commonName: "Oncidium",
      scientificName: "Oncidium spp.",
      family: "Orchidaceae",
      description: "Orchidée dansante aux nombreuses petites fleurs jaunes. Parfumée.",
      difficulty: "medium",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "50cm",
      origin: "Amérique tropicale",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière vive indirecte. Un peu de soleil matinal.",
      wateringFrequency: "Arroser quand le substrat est presque sec",
      wateringFreqDays: 5,
      humidityMin: 50, humidityMax: 70,
      tempMin: 12, tempMax: 28, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais orchidées",
      fertilizerFreqDays: 14,
      fertilizerNPK: "20-20-20",
      fertilizerNotes: "Fertiliser régulièrement en croissance",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Écorce fine, sphaigne, perlite",
      soilPH: "5.5-6.0",
      drainageNeeds: "high",
      categoryId: orchids.id,
    },
    // More tropical
    {
      commonName: "Maranta leuconeura",
      scientificName: "Maranta leuconeura",
      family: "Marantaceae",
      description: "Plante prière aux feuilles décoratives qui se replient la nuit.",
      difficulty: "medium",
      toxicity: "none",
      growthRate: "medium",
      maxHeight: "30cm",
      origin: "Brésil",
      lightMin: 2, lightMax: 3,
      lightDescription: "Lumière indirecte moyenne. Éviter le soleil direct.",
      wateringFrequency: "Maintenir légèrement humide. Eau non calcaire.",
      wateringFreqDays: 4,
      humidityMin: 50, humidityMax: 80,
      tempMin: 15, tempMax: 27, tempIdealMin: 18, tempIdealMax: 24,
      fertilizerType: "Engrais dilué plantes vertes",
      fertilizerFreqDays: 14,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Fertiliser modérément. Sensible aux excès.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Terreau riche humifère",
      soilPH: "5.5-6.0",
      drainageNeeds: "medium",
      categoryId: tropical.id,
    },
    {
      commonName: "Zamioculcas",
      scientificName: "Zamioculcas zamiifolia",
      family: "Araceae",
      description: "Plante ZZ ultra-résistante aux feuilles brillantes. Indestructible.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "slow",
      maxHeight: "1m",
      origin: "Afrique de l'Est",
      lightMin: 1, lightMax: 4,
      lightDescription: "Tolère toutes les lumières. Du sombre au vif.",
      wateringFrequency: "Laisser sécher complètement. Très résistant à la sécheresse.",
      wateringFreqDays: 14,
      humidityMin: 20, humidityMax: 60,
      tempMin: 15, tempMax: 30, tempIdealMin: 18, tempIdealMax: 25,
      fertilizerType: "Engrais équilibré dilué",
      fertilizerFreqDays: 30,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Fertiliser très peu. 2-3 fois par an suffisent.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Substrat bien drainé: terreau + perlite 50/50",
      soilPH: "6.0-7.0",
      drainageNeeds: "high",
      categoryId: tropical.id,
    },
    {
      commonName: "Sansevieria",
      scientificName: "Dracaena trifasciata",
      family: "Asparagaceae",
      description: "Langue de belle-mère. Quasi indestructible, purifie l'air.",
      difficulty: "easy",
      toxicity: "mild",
      growthRate: "slow",
      maxHeight: "1.2m",
      origin: "Afrique de l'Ouest",
      lightMin: 1, lightMax: 5,
      lightDescription: "Supporte toutes conditions de lumière.",
      wateringFrequency: "Laisser sécher complètement entre les arrosages",
      wateringFreqDays: 14,
      humidityMin: 20, humidityMax: 50,
      tempMin: 10, tempMax: 35, tempIdealMin: 18, tempIdealMax: 28,
      fertilizerType: "Engrais cactus dilué",
      fertilizerFreqDays: 30,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Fertiliser très rarement. 2-3 fois par an.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Substrat drainant: terreau + sable grossier",
      soilPH: "5.5-7.5",
      drainageNeeds: "high",
      categoryId: tropical.id,
    },
    {
      commonName: "Pilea peperomioides",
      scientificName: "Pilea peperomioides",
      family: "Urticaceae",
      description: "Plante à monnaie chinoise. Feuilles rondes sur tiges fines. Produit des rejets.",
      difficulty: "easy",
      toxicity: "none",
      growthRate: "fast",
      maxHeight: "30cm",
      origin: "Chine (Yunnan)",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière indirecte vive. Tourner régulièrement.",
      wateringFrequency: "Laisser sécher en surface entre les arrosages",
      wateringFreqDays: 7,
      humidityMin: 30, humidityMax: 60,
      tempMin: 10, tempMax: 28, tempIdealMin: 15, tempIdealMax: 24,
      fertilizerType: "Engrais plantes vertes dilué",
      fertilizerFreqDays: 14,
      fertilizerNPK: "10-10-10",
      fertilizerNotes: "Fertiliser au printemps/été. Arrêter en hiver.",
      fertilizerDoseMLPerLiter: 0.5,
      preferredSubstrate: "Terreau léger bien drainé",
      soilPH: "6.0-7.0",
      drainageNeeds: "medium",
      categoryId: tropical.id,
    },
    {
      commonName: "Begonia maculata",
      scientificName: "Begonia maculata",
      family: "Begoniaceae",
      description: "Bégonia à pois argentés sur feuilles vert foncé. Revers rouge.",
      difficulty: "medium",
      toxicity: "mild",
      growthRate: "fast",
      maxHeight: "1.5m",
      origin: "Brésil",
      lightMin: 3, lightMax: 4,
      lightDescription: "Lumière indirecte vive. Pas de soleil direct.",
      wateringFrequency: "Arroser quand le substrat sèche en surface",
      wateringFreqDays: 5,
      humidityMin: 50, humidityMax: 70,
      tempMin: 15, tempMax: 28, tempIdealMin: 18, tempIdealMax: 24,
      fertilizerType: "Engrais plantes fleuries dilué",
      fertilizerFreqDays: 14,
      fertilizerNPK: "10-20-10",
      fertilizerNotes: "Fertiliser régulièrement en croissance. Pincer pour ramifier.",
      fertilizerDoseMLPerLiter: 0.8,
      preferredSubstrate: "Terreau léger avec perlite",
      soilPH: "5.5-6.5",
      drainageNeeds: "medium",
      categoryId: tropical.id,
    },
  ];

  for (const plant of plants) {
    await prisma.plant.upsert({
      where: { id: plant.scientificName.replace(/\s/g, "-").toLowerCase() },
      update: plant,
      create: { id: plant.scientificName.replace(/\s/g, "-").toLowerCase(), ...plant },
    });
  }

  // Create substrate components
  const components = [
    { name: "Terreau universel", description: "Base organique standard", retentionFactor: 1.5, drainageFactor: 0.7, nutrientFactor: 1.3, phEffect: "neutral" },
    { name: "Perlite", description: "Roche volcanique expansée pour drainage et aération", retentionFactor: 0.3, drainageFactor: 2.0, nutrientFactor: 0.1, phEffect: "neutral" },
    { name: "Vermiculite", description: "Minéral expansé qui retient eau et nutriments", retentionFactor: 2.0, drainageFactor: 0.5, nutrientFactor: 1.5, phEffect: "neutral" },
    { name: "Écorce de pin", description: "Écorce broyée pour aération et drainage", retentionFactor: 0.5, drainageFactor: 1.8, nutrientFactor: 0.3, phEffect: "acidic" },
    { name: "Sphaigne", description: "Mousse séchée ultra-absorbante", retentionFactor: 2.5, drainageFactor: 0.4, nutrientFactor: 0.5, phEffect: "acidic" },
    { name: "Tourbe blonde", description: "Matière organique acide très absorbante", retentionFactor: 2.2, drainageFactor: 0.4, nutrientFactor: 0.4, phEffect: "acidic" },
    { name: "Fibre de coco", description: "Alternative durable à la tourbe", retentionFactor: 1.8, drainageFactor: 1.0, nutrientFactor: 0.5, phEffect: "neutral" },
    { name: "Pomice", description: "Pierre ponce volcanique ultra-drainante", retentionFactor: 0.4, drainageFactor: 2.2, nutrientFactor: 0.2, phEffect: "neutral" },
    { name: "Sable grossier", description: "Sable de rivière pour drainage", retentionFactor: 0.2, drainageFactor: 2.0, nutrientFactor: 0.0, phEffect: "neutral" },
    { name: "Charbon actif", description: "Absorbe les toxines, prévient la moisissure", retentionFactor: 0.5, drainageFactor: 1.5, nutrientFactor: 0.3, phEffect: "alkaline" },
    { name: "Zeolite", description: "Minéral qui retient nutriments et eau", retentionFactor: 1.5, drainageFactor: 1.0, nutrientFactor: 2.0, phEffect: "neutral" },
    { name: "Lave volcanique", description: "Roche poreuse pour aération permanente", retentionFactor: 0.4, drainageFactor: 1.8, nutrientFactor: 0.2, phEffect: "neutral" },
    { name: "Akadama", description: "Argile japonaise granulée. Drainage et rétention.", retentionFactor: 1.2, drainageFactor: 1.5, nutrientFactor: 1.0, phEffect: "neutral" },
    { name: "Lombricompost", description: "Compost de ver enrichi en nutriments", retentionFactor: 1.5, drainageFactor: 0.8, nutrientFactor: 2.5, phEffect: "neutral" },
    { name: "Billes d'argile", description: "Pour drainage au fond des pots", retentionFactor: 0.3, drainageFactor: 2.5, nutrientFactor: 0.0, phEffect: "neutral" },
  ];

  for (const comp of components) {
    await prisma.substrateComponent.upsert({
      where: { name: comp.name },
      update: comp,
      create: comp,
    });
  }

  console.log("✅ Seed completed: plants, categories, and substrate components created.");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
