/* eslint-disable no-console */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─────────────────────────────────────────────────────────────────────────────
// Substrates — used as fert/water modifiers (see src/lib/fertilizer.ts)
// ─────────────────────────────────────────────────────────────────────────────

const substrates = [
  {
    slug: "terreau-universel",
    name: "Terreau universel",
    description:
      "Mélange générique à base de tourbe / fibre de bois. Bonne rétention d'eau, fertilité moyenne.",
    fertMultiplier: 1.0,
    fertFrequencyShiftDays: 0,
    dryingSpeed: 1.0,
  },
  {
    slug: "terreau-plantes-vertes",
    name: "Terreau plantes vertes",
    description:
      "Pré-fertilisé pour 4 à 6 semaines, base tourbe + perlite. Rétention élevée.",
    fertMultiplier: 0.8,
    fertFrequencyShiftDays: 7,
    dryingSpeed: 0.9,
  },
  {
    slug: "melange-aroide",
    name: "Mélange aroïde (chunky)",
    description:
      "Écorce de pin + perlite + tourbe + charbon. Très drainant, idéal monstera/philodendron.",
    fertMultiplier: 1.15,
    fertFrequencyShiftDays: -2,
    dryingSpeed: 1.3,
  },
  {
    slug: "fibre-coco",
    name: "Fibre de coco",
    description:
      "100 % coco. Quasi inerte, rétention bonne, draine bien. CEC modérée.",
    fertMultiplier: 1.2,
    fertFrequencyShiftDays: -3,
    dryingSpeed: 1.1,
  },
  {
    slug: "leca",
    name: "LECA (billes d'argile)",
    description:
      "Culture semi-hydroponique. Inerte total — l'engrais doit être apporté à chaque arrosage à faible EC.",
    fertMultiplier: 1.4,
    fertFrequencyShiftDays: -7,
    dryingSpeed: 1.5,
  },
  {
    slug: "pon",
    name: "Pon (Lechuza)",
    description:
      "Mélange minéral zéolite + pierre ponce + lave. Inerte, pré-chargé en engrais ~6 mois.",
    fertMultiplier: 0.7,
    fertFrequencyShiftDays: 14,
    dryingSpeed: 1.2,
  },
  {
    slug: "terreau-cactees",
    name: "Terreau cactées & succulentes",
    description:
      "Très drainant, pauvre en matière organique. Sable + pouzzolane.",
    fertMultiplier: 0.9,
    fertFrequencyShiftDays: 0,
    dryingSpeed: 1.6,
  },
  {
    slug: "sphaigne",
    name: "Sphaigne",
    description:
      "Mousse pure. Très aéré, rétention élevée. Demande des engrais doux et fréquents.",
    fertMultiplier: 1.1,
    fertFrequencyShiftDays: -3,
    dryingSpeed: 0.8,
  },
  {
    slug: "ecorce-orchidees",
    name: "Écorce d'orchidée",
    description: "Écorce de pin calibrée. Aéré, faible CEC.",
    fertMultiplier: 1.1,
    fertFrequencyShiftDays: -2,
    dryingSpeed: 1.4,
  },
  {
    slug: "terreau-semis",
    name: "Terreau pour semis",
    description: "Fin, peu fertilisé. À fertiliser légèrement et tôt.",
    fertMultiplier: 0.7,
    fertFrequencyShiftDays: -4,
    dryingSpeed: 1.0,
  },
  {
    slug: "tourbe-blonde",
    name: "Tourbe blonde",
    description:
      "Acide (pH ~4-5), faible CEC, faible fertilité — pour plantes acidophiles (carnivores).",
    fertMultiplier: 0.3,
    fertFrequencyShiftDays: 30,
    dryingSpeed: 0.9,
  },
  {
    slug: "akadama",
    name: "Akadama",
    description: "Argile japonaise granuleuse, idéale bonsaï. Faible fertilité naturelle.",
    fertMultiplier: 1.1,
    fertFrequencyShiftDays: -2,
    dryingSpeed: 1.2,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Plant library — ~40 popular houseplants with care metadata
// ─────────────────────────────────────────────────────────────────────────────

type PlantSeed = {
  slug: string;
  commonName: string;
  latinName: string;
  family?: string;
  category: string;
  description: string;
  imageUrl?: string;
  light: string;
  minTempC: number;
  maxTempC: number;
  humidity: string;
  feeder: string;
  difficulty: string;
  toxicToPets?: boolean;
  wateringNotes?: string;
  wateringDaysSummer: number;
  wateringDaysWinter: number;
  baseDoseMlPerLiter?: number;
  fertFrequencyDaysSummer?: number;
  fertFrequencyDaysWinter?: number;
  recommendedNPK?: string;
};

const plants: PlantSeed[] = [
  {
    slug: "monstera-deliciosa",
    commonName: "Monstera deliciosa",
    latinName: "Monstera deliciosa",
    family: "Araceae",
    category: "Aroïde",
    description:
      "L'iconique « plante à trous ». Croissance rapide en lumière vive indirecte, supporte une humidité moyenne.",
    light: "BRIGHT_INDIRECT",
    minTempC: 15,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "HEAVY",
    difficulty: "EASY",
    toxicToPets: true,
    wateringNotes:
      "Laisser sécher les 2-3 premiers cm avant d'arroser. Sensible à l'excès d'eau.",
    wateringDaysSummer: 7,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 1.2,
    fertFrequencyDaysSummer: 14,
    fertFrequencyDaysWinter: 60,
    recommendedNPK: "balanced",
  },
  {
    slug: "philodendron-hederaceum",
    commonName: "Philodendron scandens",
    latinName: "Philodendron hederaceum",
    family: "Araceae",
    category: "Aroïde",
    description:
      "Liane increvable au feuillage cordiforme. Idéale en suspension ou tuteurée.",
    light: "MEDIUM",
    minTempC: 15,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 7,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 14,
    fertFrequencyDaysWinter: 60,
  },
  {
    slug: "pothos-doré",
    commonName: "Pothos doré",
    latinName: "Epipremnum aureum",
    family: "Araceae",
    category: "Aroïde",
    description:
      "Indestructible. Tolère l'ombre et oublis d'arrosage. Feuillage panaché.",
    light: "MEDIUM_LOW",
    minTempC: 13,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 8,
    wateringDaysWinter: 16,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 75,
  },
  {
    slug: "ficus-lyrata",
    commonName: "Ficus lyrata",
    latinName: "Ficus lyrata",
    family: "Moraceae",
    category: "Ficus",
    description:
      "Grandes feuilles en forme de violon. Aime la stabilité (ne pas déplacer).",
    light: "BRIGHT_INDIRECT",
    minTempC: 16,
    maxTempC: 27,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "MODERATE",
    toxicToPets: true,
    wateringNotes: "Arrosage en profondeur quand le substrat est sec sur 3 cm.",
    wateringDaysSummer: 7,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "ficus-elastica",
    commonName: "Caoutchouc",
    latinName: "Ficus elastica",
    family: "Moraceae",
    category: "Ficus",
    description: "Feuilles épaisses et brillantes. Très tolérant.",
    light: "BRIGHT_INDIRECT",
    minTempC: 15,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 7,
    wateringDaysWinter: 18,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "sansevieria-trifasciata",
    commonName: "Sansevière",
    latinName: "Dracaena trifasciata",
    family: "Asparagaceae",
    category: "Succulente",
    description: "Plante quasi indestructible. Adapte sa croissance à la lumière.",
    light: "MEDIUM",
    minTempC: 10,
    maxTempC: 32,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    toxicToPets: true,
    wateringNotes: "Laisser bien sécher entre 2 arrosages. Sensible à la pourriture.",
    wateringDaysSummer: 18,
    wateringDaysWinter: 45,
    baseDoseMlPerLiter: 0.5,
    fertFrequencyDaysSummer: 45,
    fertFrequencyDaysWinter: 120,
    recommendedNPK: "low-EC",
  },
  {
    slug: "zamioculcas-zamiifolia",
    commonName: "ZZ plant",
    latinName: "Zamioculcas zamiifolia",
    family: "Araceae",
    category: "Aroïde",
    description: "Increvable, tolère l'ombre et la sécheresse. Rhizomes charnus.",
    light: "MEDIUM_LOW",
    minTempC: 15,
    maxTempC: 30,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 14,
    wateringDaysWinter: 35,
    baseDoseMlPerLiter: 0.6,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 120,
  },
  {
    slug: "calathea-orbifolia",
    commonName: "Calathea orbifolia",
    latinName: "Goeppertia orbifolia",
    family: "Marantaceae",
    category: "Marantacée",
    description:
      "Grandes feuilles rondes striées d'argent. Capricieuse, exige humidité élevée.",
    light: "MEDIUM",
    minTempC: 18,
    maxTempC: 26,
    humidity: "HIGH",
    feeder: "MEDIUM",
    difficulty: "ADVANCED",
    wateringNotes: "Eau non calcaire (filtrée ou pluie). Substrat toujours frais.",
    wateringDaysSummer: 4,
    wateringDaysWinter: 9,
    baseDoseMlPerLiter: 0.8,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
    recommendedNPK: "low-EC",
  },
  {
    slug: "maranta-leuconeura",
    commonName: "Plante prieuse",
    latinName: "Maranta leuconeura",
    family: "Marantaceae",
    category: "Marantacée",
    description: "Replie ses feuilles la nuit. Couleurs spectaculaires.",
    light: "MEDIUM",
    minTempC: 16,
    maxTempC: 27,
    humidity: "HIGH",
    feeder: "MEDIUM",
    difficulty: "MODERATE",
    wateringDaysSummer: 5,
    wateringDaysWinter: 10,
    baseDoseMlPerLiter: 0.8,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
    recommendedNPK: "low-EC",
  },
  {
    slug: "alocasia-polly",
    commonName: "Alocasia Polly",
    latinName: "Alocasia × amazonica 'Polly'",
    family: "Araceae",
    category: "Aroïde",
    description:
      "Feuilles sagittées vert foncé veinées de blanc. Demande de l'humidité.",
    light: "BRIGHT_INDIRECT",
    minTempC: 18,
    maxTempC: 28,
    humidity: "HIGH",
    feeder: "HEAVY",
    difficulty: "ADVANCED",
    toxicToPets: true,
    wateringDaysSummer: 5,
    wateringDaysWinter: 12,
    baseDoseMlPerLiter: 1.2,
    fertFrequencyDaysSummer: 14,
    fertFrequencyDaysWinter: 75,
  },
  {
    slug: "anthurium-clarinervium",
    commonName: "Anthurium clarinervium",
    latinName: "Anthurium clarinervium",
    family: "Araceae",
    category: "Aroïde",
    description:
      "Feuilles cordiformes veloutées avec des nervures argentées proéminentes.",
    light: "MEDIUM",
    minTempC: 18,
    maxTempC: 27,
    humidity: "HIGH",
    feeder: "MEDIUM",
    difficulty: "ADVANCED",
    toxicToPets: true,
    wateringDaysSummer: 6,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 0.8,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
    recommendedNPK: "low-EC",
  },
  {
    slug: "spathiphyllum",
    commonName: "Spathiphyllum (Fleur de lune)",
    latinName: "Spathiphyllum wallisii",
    family: "Araceae",
    category: "Aroïde",
    description:
      "Floraison blanche élégante. Indique clairement la soif (feuilles tombantes).",
    light: "MEDIUM",
    minTempC: 16,
    maxTempC: 27,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 5,
    wateringDaysWinter: 10,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "hoya-carnosa",
    commonName: "Hoya carnosa",
    latinName: "Hoya carnosa",
    family: "Apocynaceae",
    category: "Hoya",
    description:
      "Liane charnue, fleurs cireuses parfumées. Vit longtemps avec peu d'eau.",
    light: "BRIGHT_INDIRECT",
    minTempC: 15,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 10,
    wateringDaysWinter: 21,
    baseDoseMlPerLiter: 0.6,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 90,
    recommendedNPK: "high-P",
  },
  {
    slug: "scindapsus-pictus",
    commonName: "Scindapsus pictus",
    latinName: "Scindapsus pictus",
    family: "Araceae",
    category: "Aroïde",
    description: "Liane au feuillage argenté. Très tolérant.",
    light: "MEDIUM",
    minTempC: 15,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    wateringDaysSummer: 7,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "begonia-maculata",
    commonName: "Bégonia maculata",
    latinName: "Begonia maculata",
    family: "Begoniaceae",
    category: "Bégonia",
    description: "Feuilles tachetées de blanc, port érigé.",
    light: "BRIGHT_INDIRECT",
    minTempC: 16,
    maxTempC: 26,
    humidity: "HIGH",
    feeder: "MEDIUM",
    difficulty: "MODERATE",
    wateringDaysSummer: 5,
    wateringDaysWinter: 12,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 14,
    fertFrequencyDaysWinter: 75,
  },
  {
    slug: "pilea-peperomioides",
    commonName: "Pilea peperomioides",
    latinName: "Pilea peperomioides",
    family: "Urticaceae",
    category: "Pilea",
    description: "Feuilles rondes en pièces de monnaie. Produit beaucoup de rejets.",
    light: "BRIGHT_INDIRECT",
    minTempC: 13,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 7,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 0.8,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "chlorophytum-comosum",
    commonName: "Plante araignée",
    latinName: "Chlorophytum comosum",
    family: "Asparagaceae",
    category: "Vivace",
    description: "Production rapide de stolons. Idéale en suspension.",
    light: "MEDIUM",
    minTempC: 10,
    maxTempC: 27,
    humidity: "LOW",
    feeder: "MEDIUM",
    difficulty: "EASY",
    wateringDaysSummer: 7,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "epipremnum-marble",
    commonName: "Pothos Marble Queen",
    latinName: "Epipremnum aureum 'Marble Queen'",
    family: "Araceae",
    category: "Aroïde",
    description: "Variégation crème prononcée. Croissance plus lente que le doré.",
    light: "BRIGHT_INDIRECT",
    minTempC: 15,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 8,
    wateringDaysWinter: 16,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "dracaena-marginata",
    commonName: "Dragonnier de Madagascar",
    latinName: "Dracaena marginata",
    family: "Asparagaceae",
    category: "Dracaena",
    description: "Tronc fin, feuillage en couronne. Très tolérant.",
    light: "MEDIUM",
    minTempC: 13,
    maxTempC: 28,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 10,
    wateringDaysWinter: 21,
    baseDoseMlPerLiter: 0.7,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 120,
  },
  {
    slug: "yucca-elephantipes",
    commonName: "Yucca",
    latinName: "Yucca gigantea",
    family: "Asparagaceae",
    category: "Vivace",
    description: "Tronc épais, feuillage en touffe. Aime la lumière directe.",
    light: "DIRECT_SUN",
    minTempC: 7,
    maxTempC: 32,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 14,
    wateringDaysWinter: 30,
    baseDoseMlPerLiter: 0.6,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 120,
  },
  {
    slug: "aloe-vera",
    commonName: "Aloe vera",
    latinName: "Aloe vera",
    family: "Asphodelaceae",
    category: "Succulente",
    description: "Succulente médicinale. Adore le soleil, déteste l'humidité.",
    light: "DIRECT_SUN",
    minTempC: 10,
    maxTempC: 32,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 18,
    wateringDaysWinter: 40,
    baseDoseMlPerLiter: 0.4,
    fertFrequencyDaysSummer: 60,
    fertFrequencyDaysWinter: 180,
    recommendedNPK: "low-EC",
  },
  {
    slug: "echeveria",
    commonName: "Echeveria",
    latinName: "Echeveria sp.",
    family: "Crassulaceae",
    category: "Succulente",
    description: "Rosettes charnues colorées. Plein soleil.",
    light: "DIRECT_SUN",
    minTempC: 8,
    maxTempC: 32,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 12,
    wateringDaysWinter: 35,
    baseDoseMlPerLiter: 0.4,
    fertFrequencyDaysSummer: 45,
    fertFrequencyDaysWinter: 180,
    recommendedNPK: "low-EC",
  },
  {
    slug: "haworthia",
    commonName: "Haworthia",
    latinName: "Haworthia sp.",
    family: "Asphodelaceae",
    category: "Succulente",
    description: "Petite succulente d'intérieur. Tolère un peu d'ombre.",
    light: "BRIGHT_INDIRECT",
    minTempC: 8,
    maxTempC: 30,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 14,
    wateringDaysWinter: 40,
    baseDoseMlPerLiter: 0.4,
    fertFrequencyDaysSummer: 60,
    fertFrequencyDaysWinter: 180,
  },
  {
    slug: "cactus-mammillaria",
    commonName: "Cactus Mammillaria",
    latinName: "Mammillaria sp.",
    family: "Cactaceae",
    category: "Cactée",
    description: "Petits cactus globuleux à fleurs. Demande très peu d'eau.",
    light: "DIRECT_SUN",
    minTempC: 5,
    maxTempC: 35,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 18,
    wateringDaysWinter: 60,
    baseDoseMlPerLiter: 0.4,
    fertFrequencyDaysSummer: 45,
    fertFrequencyDaysWinter: 180,
    recommendedNPK: "low-EC",
  },
  {
    slug: "ferocactus",
    commonName: "Ferocactus",
    latinName: "Ferocactus sp.",
    family: "Cactaceae",
    category: "Cactée",
    description: "Cactus barillets à grosses épines. Plein soleil.",
    light: "DIRECT_SUN",
    minTempC: 5,
    maxTempC: 35,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "MODERATE",
    wateringDaysSummer: 20,
    wateringDaysWinter: 75,
    baseDoseMlPerLiter: 0.4,
    fertFrequencyDaysSummer: 60,
    fertFrequencyDaysWinter: 240,
    recommendedNPK: "low-EC",
  },
  {
    slug: "nepenthes",
    commonName: "Népenthès (plante carnivore)",
    latinName: "Nepenthes sp.",
    family: "Nepenthaceae",
    category: "Carnivore",
    description:
      "Plante à urnes carnivore. Eau pluviale uniquement, jamais d'engrais minéral classique.",
    light: "BRIGHT_INDIRECT",
    minTempC: 15,
    maxTempC: 30,
    humidity: "VERY_HIGH",
    feeder: "LIGHT",
    difficulty: "ADVANCED",
    wateringNotes:
      "Substrat toujours humide. Eau pluviale obligatoire. Engrais foliaire dilué uniquement.",
    wateringDaysSummer: 2,
    wateringDaysWinter: 5,
    baseDoseMlPerLiter: 0.1,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 90,
    recommendedNPK: "low-EC",
  },
  {
    slug: "dionaea-muscipula",
    commonName: "Dionée attrape-mouche",
    latinName: "Dionaea muscipula",
    family: "Droseraceae",
    category: "Carnivore",
    description: "Pièges à mâchoires. Aucun engrais. Eau de pluie/distillée stricte.",
    light: "DIRECT_SUN",
    minTempC: 5,
    maxTempC: 32,
    humidity: "HIGH",
    feeder: "LIGHT",
    difficulty: "ADVANCED",
    wateringNotes:
      "Méthode du sous-pot : 1-2 cm d'eau distillée en permanence en été, sec en hiver (dormance).",
    wateringDaysSummer: 2,
    wateringDaysWinter: 7,
    baseDoseMlPerLiter: 0.0,
    fertFrequencyDaysSummer: 365,
    fertFrequencyDaysWinter: 365,
  },
  {
    slug: "phalaenopsis",
    commonName: "Orchidée Phalaenopsis",
    latinName: "Phalaenopsis sp.",
    family: "Orchidaceae",
    category: "Orchidée",
    description:
      "Orchidée d'intérieur la plus répandue. Floraison longue, racines aériennes.",
    light: "BRIGHT_INDIRECT",
    minTempC: 16,
    maxTempC: 28,
    humidity: "HIGH",
    feeder: "LIGHT",
    difficulty: "MODERATE",
    wateringNotes:
      "Tremper le pot 10 min toutes les 1-2 semaines, laisser bien égoutter. Aucune eau dans le cœur.",
    wateringDaysSummer: 8,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 0.5,
    fertFrequencyDaysSummer: 14,
    fertFrequencyDaysWinter: 30,
    recommendedNPK: "low-EC",
  },
  {
    slug: "fougere-de-boston",
    commonName: "Fougère de Boston",
    latinName: "Nephrolepis exaltata",
    family: "Nephrolepidaceae",
    category: "Fougère",
    description: "Fougère populaire au feuillage retombant. Humidité élevée requise.",
    light: "MEDIUM",
    minTempC: 13,
    maxTempC: 26,
    humidity: "HIGH",
    feeder: "MEDIUM",
    difficulty: "MODERATE",
    wateringDaysSummer: 4,
    wateringDaysWinter: 10,
    baseDoseMlPerLiter: 0.7,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "asplenium-nidus",
    commonName: "Nid d'oiseau",
    latinName: "Asplenium nidus",
    family: "Aspleniaceae",
    category: "Fougère",
    description: "Fougère épiphyte aux frondes brillantes en rosette.",
    light: "MEDIUM",
    minTempC: 16,
    maxTempC: 27,
    humidity: "HIGH",
    feeder: "LIGHT",
    difficulty: "MODERATE",
    wateringDaysSummer: 5,
    wateringDaysWinter: 12,
    baseDoseMlPerLiter: 0.5,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 120,
  },
  {
    slug: "platycerium-bifurcatum",
    commonName: "Corne d'élan",
    latinName: "Platycerium bifurcatum",
    family: "Polypodiaceae",
    category: "Fougère",
    description:
      "Fougère épiphyte spectaculaire à monter sur plaque. Aime l'humidité.",
    light: "BRIGHT_INDIRECT",
    minTempC: 15,
    maxTempC: 28,
    humidity: "HIGH",
    feeder: "LIGHT",
    difficulty: "MODERATE",
    wateringDaysSummer: 6,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 0.5,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 120,
  },
  {
    slug: "tradescantia-zebrina",
    commonName: "Misère Zebrina",
    latinName: "Tradescantia zebrina",
    family: "Commelinaceae",
    category: "Vivace",
    description: "Feuillage rayé pourpre et argent. Pousse à vue d'œil.",
    light: "BRIGHT_INDIRECT",
    minTempC: 13,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    wateringDaysSummer: 5,
    wateringDaysWinter: 12,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 14,
    fertFrequencyDaysWinter: 60,
  },
  {
    slug: "peperomia-obtusifolia",
    commonName: "Peperomia obtusifolia",
    latinName: "Peperomia obtusifolia",
    family: "Piperaceae",
    category: "Peperomia",
    description: "Petite plante semi-succulente compacte, feuilles épaisses.",
    light: "MEDIUM",
    minTempC: 15,
    maxTempC: 27,
    humidity: "AVERAGE",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 10,
    wateringDaysWinter: 21,
    baseDoseMlPerLiter: 0.6,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 120,
  },
  {
    slug: "syngonium-podophyllum",
    commonName: "Syngonium",
    latinName: "Syngonium podophyllum",
    family: "Araceae",
    category: "Aroïde",
    description: "Aroïde grimpant aux feuilles évoluant en flèche.",
    light: "MEDIUM",
    minTempC: 15,
    maxTempC: 28,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 7,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "monstera-adansonii",
    commonName: "Monstera adansonii",
    latinName: "Monstera adansonii",
    family: "Araceae",
    category: "Aroïde",
    description:
      "« Swiss cheese plant » : feuilles ovales trouées. Liane vigoureuse.",
    light: "BRIGHT_INDIRECT",
    minTempC: 16,
    maxTempC: 28,
    humidity: "HIGH",
    feeder: "HEAVY",
    difficulty: "MODERATE",
    toxicToPets: true,
    wateringDaysSummer: 6,
    wateringDaysWinter: 12,
    baseDoseMlPerLiter: 1.2,
    fertFrequencyDaysSummer: 14,
    fertFrequencyDaysWinter: 60,
  },
  {
    slug: "philodendron-birkin",
    commonName: "Philodendron Birkin",
    latinName: "Philodendron 'Birkin'",
    family: "Araceae",
    category: "Aroïde",
    description: "Feuillage vert strié de blanc. Port compact.",
    light: "BRIGHT_INDIRECT",
    minTempC: 16,
    maxTempC: 27,
    humidity: "AVERAGE",
    feeder: "MEDIUM",
    difficulty: "EASY",
    toxicToPets: true,
    wateringDaysSummer: 7,
    wateringDaysWinter: 14,
    baseDoseMlPerLiter: 1.0,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "stromanthe-triostar",
    commonName: "Stromanthe Triostar",
    latinName: "Stromanthe sanguinea 'Triostar'",
    family: "Marantaceae",
    category: "Marantacée",
    description: "Feuillage panaché rose, blanc et vert. Très décoratif.",
    light: "BRIGHT_INDIRECT",
    minTempC: 16,
    maxTempC: 27,
    humidity: "HIGH",
    feeder: "MEDIUM",
    difficulty: "ADVANCED",
    wateringDaysSummer: 5,
    wateringDaysWinter: 10,
    baseDoseMlPerLiter: 0.8,
    fertFrequencyDaysSummer: 21,
    fertFrequencyDaysWinter: 90,
    recommendedNPK: "low-EC",
  },
  {
    slug: "fittonia-albivenis",
    commonName: "Fittonia",
    latinName: "Fittonia albivenis",
    family: "Acanthaceae",
    category: "Vivace",
    description: "Petit couvre-sol à veines blanches/roses. Terrariums.",
    light: "MEDIUM",
    minTempC: 16,
    maxTempC: 26,
    humidity: "HIGH",
    feeder: "MEDIUM",
    difficulty: "MODERATE",
    wateringDaysSummer: 3,
    wateringDaysWinter: 7,
    baseDoseMlPerLiter: 0.7,
    fertFrequencyDaysSummer: 30,
    fertFrequencyDaysWinter: 90,
  },
  {
    slug: "ceropegia-woodii",
    commonName: "Chaîne des cœurs",
    latinName: "Ceropegia woodii",
    family: "Apocynaceae",
    category: "Vivace",
    description:
      "Suspension délicate aux feuilles en forme de cœur. Tolère l'oubli d'arrosage.",
    light: "BRIGHT_INDIRECT",
    minTempC: 13,
    maxTempC: 28,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "EASY",
    wateringDaysSummer: 14,
    wateringDaysWinter: 35,
    baseDoseMlPerLiter: 0.4,
    fertFrequencyDaysSummer: 45,
    fertFrequencyDaysWinter: 180,
  },
  {
    slug: "senecio-rowleyanus",
    commonName: "Collier de perles",
    latinName: "Curio rowleyanus",
    family: "Asteraceae",
    category: "Succulente",
    description: "Succulente retombante aux feuilles sphériques. Soleil.",
    light: "DIRECT_SUN",
    minTempC: 10,
    maxTempC: 30,
    humidity: "LOW",
    feeder: "LIGHT",
    difficulty: "MODERATE",
    wateringDaysSummer: 14,
    wateringDaysWinter: 40,
    baseDoseMlPerLiter: 0.4,
    fertFrequencyDaysSummer: 45,
    fertFrequencyDaysWinter: 180,
    recommendedNPK: "low-EC",
  },
];

async function main() {
  console.log("Seeding substrates…");
  for (const s of substrates) {
    await prisma.substrate.upsert({
      where: { slug: s.slug },
      update: s,
      create: s,
    });
  }
  console.log(`✔ ${substrates.length} substrates seeded`);

  console.log("Seeding plants…");
  for (const p of plants) {
    await prisma.plant.upsert({
      where: { slug: p.slug },
      update: p,
      create: p,
    });
  }
  console.log(`✔ ${plants.length} plants seeded`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
